### PR TITLE
added java files

### PR DESCRIPTION
**Pull request by AlexS54**

### CODE REVIEW

**Comment by EmanuelRaileanu** [comment]
Commit message not suggestive enough, otherwise, well done.

**Comment by VladRaileanu** [comment]
10/10 would merge again

**Review by EmanuelRaileanu — APPROVED** [review]
Downvoted my constructive criticism message for some reason. Otherwise it is good.

**Comment by aflaviusandrei** [comment]
` public void connect() {
  }

  public void disconnect() {
  }

  public void getUnivLayout() {
  }`

Methods seem to be empty? Implementation pending?

Please return when you have proper functionality.

**Pull request merged**
